AllCops:
  EnabledByDefault: true
  Exclude:
    - 'tmp/**/*'
    - 'db/**/*.rb'
    - '**/schema.rb'
    - 'lib/tasks/**/*.rake'
    - 'bin/**/*'
  TargetRubyVersion: 3.0.4

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/HeredocIndentation:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'db/**/*.rb'
    - '**/schema.rb'
    - 'config/**/*.rb'

Style/RedundantSelf:
  Enabled: false
