version: '3.5'

volumes:
  db_data:

services:
  base: &base
    working_dir: /ceap
    ports: []
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/ceap
    depends_on:
    - db

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  app:
    <<: *base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    ports:
      - 3000:3000

  specs:
    <<: *base
    command: /bin/bash -c "rails db:test:prepare && bundle exec rspec spec"
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db:5432/acme_test
