version: '3.5'

volumes:
  db_data:
  redis-data:

services:
  base: &base
    working_dir: /ceap
    ports: []
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/ceap
    depends_on:
      - db
      - redis
      - sidekiq

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  sidekiq:
    command: bundle exec sidekiq -C config/sidekiq.yml
    build: .
    tty: true
    env_file: .env
    volumes:
      - .:/ceap
    depends_on:
      - db
      - redis

  app:
    <<: *base
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    env_file: .env
    ports:
      - 3000:3000

  specs:
    <<: *base
    command: /bin/bash -c "rails db:test:prepare && bundle exec rspec spec"
    environment:
      RAILS_ENV: test
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:password@db:5432/ceap_test
