version: '3'

volumes:
  db_data:

services:
  base: &base
    hostname: app
    working_dir: /workspace
    ports: []
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment: &env
      RAILS_ENV: development
      HOST: http://localhost:3000
    volumes:
      - .:/workspace

  db:
    hostname: db
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: vitor@1234
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
    - 6003:6003
    environment:
      PGADMIN_DEFAULT_EMAIL: email@yopmail.com
      PGADMIN_DEFAULT_PASSWORD: vitor@1234
    depends_on:
    - db

  app:
    <<: *base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: vitor@1234
    ports:
      - 3000:3000
    depends_on:
      - db

  rubocop:
    <<: *base
    command: /bin/ash -c "bundle exec rake lint"
