default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV['DATABASE_TIMEOUT'] || '5000' %>
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode

development:
  <<: *default
  database: ceap_development

test:
  <<: *default
  database: ceap_test

production: *default
